# Generated by Django 4.2.4 on 2023-11-03 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.SmallIntegerField(choices=[(1, '激活'), (2, '删除')], default=1, verbose_name='账号状态')),
                ('username', models.CharField(db_index=True, max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('mobile', models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.SmallIntegerField(choices=[(1, '激活'), (2, '删除')], default=1, verbose_name='账号状态')),
                ('username', models.CharField(db_index=True, max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('mobile', models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.SmallIntegerField(choices=[(1, '激活'), (2, '删除')], default=1, verbose_name='账号状态')),
                ('username', models.CharField(db_index=True, max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('mobile', models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.SmallIntegerField(choices=[(1, '激活'), (2, '删除')], default=1, verbose_name='账号状态')),
                ('charge_type', models.SmallIntegerField(choices=[(1, '测试完成'), (2, '不需要测试'), (3, '待启动'), (4, '测试阻塞'), (5, '测试中')], verbose_name='类型')),
                ('order_oid', models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='测试单号')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='任务创建时间')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='任务开始时间')),
                ('finish_time', models.DateTimeField(auto_now_add=True, verbose_name='任务完成时间')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Light.administrator', verbose_name='管理员')),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Light.developer', verbose_name='开发人员')),
                ('tester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Light.tester', verbose_name='测试员')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.SmallIntegerField(choices=[(1, '激活'), (2, '删除')], default=1, verbose_name='账号状态')),
                ('status', models.SmallIntegerField(choices=[(1, '待启动'), (2, '测试中'), (3, '已完成测试'), (4, '测试阻塞'), (5, '不需要测试')], default=1, verbose_name='状态')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('start_datetime', models.DateTimeField(verbose_name='开始时间')),
                ('finish_datetime', models.DateTimeField(verbose_name='完成时间')),
                ('oid', models.CharField(max_length=64, unique=True, verbose_name='订单号')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Light.developer', verbose_name='开发人员')),
                ('tester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Light.tester', verbose_name='测试人员')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
