# Generated by Django 4.2.4 on 2023-11-03 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Light', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='入职时间'),
        ),
        migrations.AlterField(
            model_name='task',
            name='oid',
            field=models.CharField(max_length=64, unique=True, verbose_name='测试单号'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '待启动'), (2, '测试中'), (3, '已完成测试'), (4, '测试阻塞'), (5, '不需要测试')], default=1, verbose_name='测试状态'),
        ),
        migrations.AlterField(
            model_name='tester',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='入职时间'),
        ),
    ]
