# Generated by Django 4.2.4 on 2023-11-04 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Light', '0002_alter_developer_create_date_alter_task_oid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tester',
            name='is_admin',
            field=models.SmallIntegerField(choices=[(0, '不具有'), (1, '具有')], default=0, verbose_name='是否具有管理员权限'),
        ),
        migrations.AlterField(
            model_name='testrecord',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creater', to='Light.tester', verbose_name='创建者'),
        ),
        migrations.DeleteModel(
            name='Administrator',
        ),
    ]
