# Generated by Django 4.2.4 on 2023-11-04 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Light', '0003_tester_is_admin_alter_testrecord_creator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='is_admin',
            field=models.SmallIntegerField(choices=[(0, '不具有'), (1, '具有')], default=0, verbose_name='是否具有管理员权限'),
        ),
    ]
