# Generated by Django 4.2.4 on 2023-11-06 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Light', '0004_developer_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='name',
            field=models.CharField(db_index=True, default='开发xxx', max_length=32, verbose_name='姓名'),
        ),
        migrations.AddField(
            model_name='tester',
            name='name',
            field=models.CharField(db_index=True, default='测试xxx', max_length=32, verbose_name='姓名'),
        ),
    ]
