# Generated by Django 4.2.4 on 2023-11-06 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Light', '0005_developer_name_tester_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='name',
            field=models.CharField(db_index=True, max_length=32, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='developer',
            name='password',
            field=models.CharField(default='12345', max_length=64, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='tester',
            name='name',
            field=models.CharField(db_index=True, max_length=32, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='tester',
            name='password',
            field=models.CharField(default='12345', max_length=64, verbose_name='密码'),
        ),
    ]
