# Generated by Django 4.2.4 on 2023-11-06 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Light', '0006_alter_developer_name_alter_developer_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='password',
            field=models.CharField(default='12345', help_text='默认为12345', max_length=64, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='tester',
            name='password',
            field=models.CharField(default='12345', help_text='默认为12345', max_length=64, verbose_name='密码'),
        ),
    ]
