# Generated by Django 4.2.4 on 2023-11-06 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Light', '0007_alter_developer_password_alter_tester_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tester',
            name='password',
            field=models.CharField(default='12345', max_length=64, verbose_name='密码'),
        ),
    ]
