# Generated by Django 4.2.4 on 2023-11-06 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Light', '0009_alter_developer_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='finish_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='完成时间'),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='开始时间'),
        ),
    ]
