# Generated by Django 4.2.4 on 2023-11-06 16:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Light', '0010_alter_task_finish_datetime_alter_task_start_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=64, verbose_name='测试任务名'),
            preserve_default=False,
        ),
    ]
