# Generated by Django 4.2.4 on 2023-11-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Light', '0011_task_task_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '待启动'), (2, '测试中'), (3, '已完成测试'), (4, '测试暂停')], default=1, verbose_name='测试状态'),
        ),
    ]
