# Generated by Django 4.2.4 on 2023-11-15 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Light', '0012_alter_task_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='developer',
        ),
        migrations.RemoveField(
            model_name='task',
            name='tester',
        ),
        migrations.AddField(
            model_name='task',
            name='developer',
            field=models.ManyToManyField(to='Light.developer'),
        ),
        migrations.AddField(
            model_name='task',
            name='tester',
            field=models.ManyToManyField(to='Light.tester'),
        ),
    ]
